### ISSUE TITLE
Ansible galaxy install fails

### ISSUE THREAD

**Issue by fnzv** [sunfoxcz/ansible-dkim#13]
Hi there!
I was trying your role and seems like that the release url is not picked up by ansible-galaxy:

```
$ ansible-galaxy install sunfoxcz.dkim -p .
- downloading role 'dkim', owned by sunfoxcz
- downloading role from https://github.com/FoxyRoles/ansible-dkim/archive/v1.0.0.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - sunfoxcz.dkim was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Dunno if something changed on your galaxy account or it's just a naming issue of github release

**Comment by foxycode** [comment]
Looks like Galaxy is using release name as part of file path instead of tag name. I renamed releases, but don§t know how to update role on galaxy. Can you advise?

**Comment by foxycode** [comment]
@fnzv I figured it out :) Try it now, new version should be available.

**Comment by fnzv** [comment]
Perfect! Now requirements are downloaded correctly
