### ISSUE TITLE
common practise here asked, for keys rotation / initial setup, and key publication in dns

### ISSUE THREAD

**Issue by mjhgthb** [sunfoxcz/ansible-dkim#20]
Hi,
The script works nicely for generating keys and putting them into postfix. Super, thanks!

But we wonder about the order of things: should the keys keys not be added to dns first, wait for dns propagation, and once that is complete: configure postfix to start signing.

The way I look at ansible-dkim now, the order is reversed: you run the script, keys are generated, postfix is configured & restarted: off you go. But nothing in DNS yet.

Is there logic or a way to upload keys to dns FIRST, and LATER start using them on postfix?
(question is both for initial setup, but also for keys rotation: rotated keys need to published first, and THEN start using them)

Any feedback? Or are we missing something?

**Comment by foxycode** [comment]
This is only simple role to make things easier than setting all by hand. I never planned automatic DNS updates. Everyone have DNS at different provider, it would be too complex.

You can always disable signing for specific domains by hand and activate them after you have keys in DNS.

**Comment by mjhgthb** [comment]
Yes, understood. Not asking about dns updates. That is my own problem to sort out.

I'm asking if there is a way to run the script to generate and put in place everything new, but to skip [for now] the edits of KeyTable/SigningTable.

This would give us the time to edit dns, wait for propagation, etc, and then run the script again, WITH altering KeyTable/SigningTable, restart opendkim, and then postfix/opendkim would start using the new keys.

**Comment by foxycode** [comment]
I don't know how that would work. I'm ok with that if you can find simple enought way.

**Comment by mjhgthb** [comment]
sent a merge request, meant as a simple proposal
