### ISSUE TITLE
Ansible Galaxy Role

### ISSUE THREAD

**Issue by foxycode** [sunfoxcz/ansible-dkim#7]
I added role to Galaxy: https://galaxy.ansible.com/sunfoxcz/dkim

@ulvida Can you please check if it works? I don't use Galaxy yet.

**Comment by ulvida** [comment]
Good! I was being searching your... sorry, our role in the Galaxy, and then wanted to talk you about it.
Ok, I take this task. It will simply mean changing role's reference in [our platform](https://git.interior.edu.uy/cielito/adminsys/#cielitoadminsys-el-espacio-colaborativo-p%C3%BAblico-de-la-red-de-unidades-inform%C3%A1ticas-de-la-udelar-en-el-interior), and do some test as we rountinly do to deploy things.

**Comment by foxycode** [comment]
@ulvida Any news about role? Did you tested it?

**Comment by ulvida** [comment]
Hello @foxycode Sorry for my silence!
I put the reference to our role in the galaxy in our `requirements.yml`on jun 22th, and test it on a single configuration the same day. But that's not an exhaustive test, and maybe it can be good to have an external view for test. Let me ask to my colleague @santiagomr to do a review with us.

**Comment by foxycode** [comment]
This was already fixed on Galaxy
